MAPS_ANDROID_KEY=AIzaSyBFDK6Fk7DqHFvDRU-9pZ3UKiM-I0uCSVY
BIS_SERVICE_KEY=954bc62072d71da094fd48756ad0d64cd196cfcf915c8c6090ce17e3b6a0f282

# AndroidX settings
android.useAndroidX=true
android.enableJetifier=true

# Gradle memory settings
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
